# Generated by Django 3.2.12 on 2022-09-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
