# Generated by Django 4.1.1 on 2022-09-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_posts_last_edited"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("content", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name="posts",
            options={"ordering": ("-date_created",)},
        ),
        migrations.AddField(
            model_name="posts",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.category",
            ),
            preserve_default=False,
        ),
    ]
