# Generated by Django 4.1.1 on 2022-09-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_category_alter_posts_options_posts_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="posts",
            options={
                "ordering": ("-date_created",),
                "verbose_name_plural": "Posts",
            },
        ),
    ]
