# Generated by Django 4.1.1 on 2022-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="11", max_length=200),
            preserve_default=False,
        ),
    ]
