# Generated by Django 4.1.1 on 2022-10-13 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=200
            ),
            preserve_default=False,
        ),
    ]
